# Generated by Django 6.0.6 on 2026-06-20 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expeditions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expedition",
            name="chief",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="led_expeditions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expeditionmember",
            name="expedition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="expeditions.expedition",
            ),
        ),
        migrations.AddField(
            model_name="expeditionmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expedition_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="expeditionmember",
            constraint=models.UniqueConstraint(
                fields=("expedition", "user"), name="unique_expedition_member"
            ),
        ),
    ]
