# Generated by Django 6.0.6 on 2026-06-20 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expeditions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expedition",
            index=models.Index(fields=["status"], name="expedition_status_idx"),
        ),
        migrations.AddIndex(
            model_name="expedition",
            index=models.Index(fields=["chief"], name="expedition_chief_idx"),
        ),
        migrations.AddIndex(
            model_name="expeditionmember",
            index=models.Index(
                fields=["user", "state"], name="exp_member_user_state_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expeditionmember",
            index=models.Index(
                fields=["expedition", "state"], name="exp_member_exp_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="expedition",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gte", 1)),
                name="expedition_capacity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="expedition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_at__isnull", True),
                    ("end_at__gte", models.F("start_at")),
                    _connector="OR",
                ),
                name="expedition_end_at_after_start_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="expeditionmember",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("confirmed_at__isnull", True), ("state", "invited")),
                    models.Q(("confirmed_at__isnull", False), ("state", "confirmed")),
                    _connector="OR",
                ),
                name="expedition_member_confirmed_at_matches_state",
            ),
        ),
    ]
