# Generated by Django 6.0.6 on 2026-06-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expeditions", "0003_expedition_expedition_status_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="expeditionmember",
            name="expedition_member_confirmed_at_matches_state",
        ),
        migrations.RemoveIndex(
            model_name="expedition",
            name="expedition_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="expedition",
            name="expedition_chief_idx",
        ),
        migrations.RemoveIndex(
            model_name="expeditionmember",
            name="exp_member_user_state_idx",
        ),
        migrations.RemoveIndex(
            model_name="expeditionmember",
            name="exp_member_exp_state_idx",
        ),
    ]
